mesos-cluster-config:
    servers:
        ip_1: '192.168.100.101'
        ip_2: '192.168.100.102'
        ip_3: '192.168.100.103'
    zookeeper:
        docker_image_name: 'mesoscloud/zookeeper:3.4.6-ubuntu-14.04'
    mesos-master:
        docker_image_name: 'mesoscloud/mesos-master:0.23.0-ubuntu-14.04'
    mesos-slave:
        docker_image_name: 'mesoscloud/mesos-slave:0.23.0-ubuntu-14.04'